"use client";

import { useCallback, useEffect, useState } from "react";
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from "recharts";
import {
  Bell, ShoppingBag, UtensilsCrossed, Users, DollarSign,
  CheckCircle2, Filter, Search, Plus, Settings, ChevronRight, Mail,
  X, ArrowLeft, ExternalLink, Clock, Tag, Layers, Wifi,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { FadeIn, SlideUp, ScaleIn, StaggerContainer, StaggerItem } from "@/components/ui";
import { Button } from "@/components/ui";
import {
  useNotifications,
  type Notification,
  type Priority,
} from "@/components/meal-service/NotificationsContext";

/* ── Static display maps ────────────────────────────────────────────────── */
const TYPE_ICON: Record<string, typeof Bell> = {
  order: ShoppingBag, meal: UtensilsCrossed, user: Users, finance: DollarSign, system: Bell,
};
const TYPE_BG: Record<string, string> = {
  order: "bg-indigo-50", meal: "bg-emerald-50", user: "bg-sky-50", finance: "bg-violet-50", system: "bg-slate-100",
};
const TYPE_ICON_COLOR: Record<string, string> = {
  order: "text-indigo-600", meal: "text-emerald-600", user: "text-sky-600", finance: "text-violet-600", system: "text-slate-500",
};
const TYPE_ACCENT: Record<string, string> = {
  order: "border-indigo-200 bg-indigo-50", meal: "border-emerald-200 bg-emerald-50",
  user: "border-sky-200 bg-sky-50", finance: "border-violet-200 bg-violet-50", system: "border-slate-200 bg-slate-50",
};
const PRIORITY_STYLE: Record<Priority, string> = {
  high:   "bg-rose-50 text-rose-700 border-rose-200",
  medium: "bg-amber-50 text-amber-700 border-amber-200",
  low:    "bg-slate-100 text-slate-500 border-slate-200",
};

/* Mock extended body per notification type */
const TYPE_BODY: Record<string, string> = {
  order:   "The order has been logged in the system and is awaiting kitchen confirmation. You can view the full order breakdown, assign it to a delivery slot, or issue a cancellation from the Orders module.",
  meal:    "This is a scheduled reminder generated by the Meal Plan engine. Confirm meal availability with kitchen staff and update the delivery status once the meal has been dispatched.",
  user:    "A change was detected in the member registry. Review the updated profile to ensure role assignments, dietary preferences, and plan allocations are correctly set.",
  finance: "A financial transaction has been recorded. Cross-reference with your billing records and confirm that the corresponding invoice status has been updated to reflect this payment.",
  system:  "This is an automated system notification. No immediate action is required unless stated in the message body above. Archive this notification once reviewed.",
};

const TYPE_ACTIONS: Record<string, { label: string; primary?: boolean }[]> = {
  order:   [{ label: "View Order", primary: true }, { label: "Assign Delivery" }, { label: "Cancel Order" }],
  meal:    [{ label: "View Meal Plan", primary: true }, { label: "Update Status" }],
  user:    [{ label: "View Profile", primary: true }, { label: "Edit Permissions" }],
  finance: [{ label: "View Invoice", primary: true }, { label: "Download Receipt" }],
  system:  [{ label: "View Report", primary: true }, { label: "Archive" }],
};

const CHANNEL_DATA = [
  { name: "App",   value: 56, color: "#6366f1" },
  { name: "Email", value: 24, color: "#22c55e" },
  { name: "SMS",   value: 10, color: "#f59e0b" },
  { name: "Push",  value: 10, color: "#f43f5e" },
];

const TABS = ["All", "Unread", "Read", "Order & Delivery", "Meal & Menu", "User & Staff", "Finance"] as const;
type Tab = typeof TABS[number];

const PAGE_SIZE = 8;

/* ── Notification detail panel ──────────────────────────────────────────── */
function DetailPanel({
  notification,
  onClose,
}: {
  notification: Notification;
  onClose: () => void;
}) {
  const Icon    = TYPE_ICON[notification.type];
  const actions = TYPE_ACTIONS[notification.type] ?? [];
  const body    = TYPE_BODY[notification.type] ?? "";

  /* Close on Escape */
  useEffect(() => {
    function onKey(e: KeyboardEvent) { if (e.key === "Escape") onClose(); }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <>
      {/* Backdrop */}
      <motion.div
        key="backdrop"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.2 }}
        onClick={onClose}
        className="fixed inset-0 z-30 bg-black/20 backdrop-blur-[2px] lg:hidden"
      />

      {/* Panel */}
      <motion.div
        key="panel"
        initial={{ x: "100%", opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        exit={{ x: "100%", opacity: 0 }}
        transition={{ type: "spring", stiffness: 340, damping: 32 }}
        className="fixed inset-y-0 right-0 z-40 flex w-full max-w-sm flex-col bg-white shadow-2xl lg:static lg:inset-auto lg:z-auto lg:max-w-none lg:shadow-none lg:rounded-xl lg:border lg:border-slate-200"
      >
        {/* Panel header */}
        <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3">
          <button
            type="button"
            onClick={onClose}
            className="flex items-center gap-1.5 text-xs font-medium text-slate-500 hover:text-slate-800 transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back
          </button>
          <span className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">
            Notification Detail
          </span>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700 transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto p-4">
          {/* Icon + title */}
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.05 }}
            className="flex items-start gap-3"
          >
            <motion.div
              initial={{ scale: 0.7, rotate: -8 }}
              animate={{ scale: 1, rotate: 0 }}
              transition={{ type: "spring", stiffness: 400, damping: 22, delay: 0.08 }}
              className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border ${TYPE_ACCENT[notification.type]}`}
            >
              <Icon className={`h-5 w-5 ${TYPE_ICON_COLOR[notification.type]}`} />
            </motion.div>
            <div className="min-w-0 flex-1">
              <p className="text-sm font-bold leading-snug text-slate-900">{notification.title}</p>
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold capitalize ${PRIORITY_STYLE[notification.priority]}`}>
                  {notification.priority} priority
                </span>
                <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold capitalize ${
                  notification.status === "unread"
                    ? "bg-indigo-50 text-indigo-700 border-indigo-200"
                    : "bg-slate-100 text-slate-500 border-slate-200"
                }`}>
                  {notification.status}
                </span>
              </div>
            </div>
          </motion.div>

          {/* Summary */}
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.1 }}
            className="mt-4 text-sm leading-relaxed text-slate-700"
          >
            {notification.subtitle}
          </motion.p>

          {/* Extended body */}
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.14 }}
            className="mt-2 text-[12px] leading-relaxed text-slate-500"
          >
            {body}
          </motion.p>

          {/* Metadata grid */}
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.18 }}
            className="mt-5 rounded-xl border border-slate-100 bg-slate-50 p-3"
          >
            <p className="mb-2.5 text-[10px] font-semibold uppercase tracking-wider text-slate-400">Details</p>
            <div className="grid grid-cols-2 gap-2">
              {[
                { icon: Layers,  label: "Module",   value: notification.module },
                { icon: Tag,     label: "Type",     value: notification.type,  capitalize: true },
                { icon: Clock,   label: "Received", value: notification.date },
                { icon: Wifi,    label: "Channel",  value: "In-App" },
              ].map(({ icon: MetaIcon, label, value, capitalize }) => (
                <div key={label} className="flex flex-col gap-0.5">
                  <div className="flex items-center gap-1 text-[10px] text-slate-400">
                    <MetaIcon className="h-3 w-3" />
                    {label}
                  </div>
                  <p className={`text-[11px] font-semibold text-slate-700 ${capitalize ? "capitalize" : ""}`}>
                    {value}
                  </p>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Related / timeline stub */}
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.22 }}
            className="mt-4"
          >
            <p className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-slate-400">Timeline</p>
            <div className="flex flex-col gap-0">
              {[
                { label: "Notification triggered", time: notification.date,            dot: "bg-indigo-500" },
                { label: "Delivered to app inbox",  time: notification.date,            dot: "bg-emerald-400" },
                { label: "Opened by user",          time: "Just now",                  dot: "bg-slate-300" },
              ].map((ev, i) => (
                <div key={i} className="flex items-start gap-2.5 pb-3 relative">
                  {i < 2 && (
                    <span className="absolute left-[5px] top-3 h-full w-px bg-slate-100" />
                  )}
                  <span className={`relative mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${ev.dot} ring-2 ring-white`} />
                  <div>
                    <p className="text-[11px] font-medium text-slate-700">{ev.label}</p>
                    <p className="text-[10px] text-slate-400">{ev.time}</p>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>
        </div>

        {/* Footer actions */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25 }}
          className="border-t border-slate-100 p-4 flex flex-col gap-2"
        >
          {actions.map((a, i) => (
            <motion.button
              key={a.label}
              type="button"
              initial={{ opacity: 0, x: 8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.28 + i * 0.05 }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className={`flex w-full items-center justify-center gap-1.5 rounded-lg px-3 py-2.5 text-xs font-semibold transition-colors ${
                a.primary
                  ? "bg-indigo-600 text-white hover:bg-indigo-700"
                  : "border border-slate-200 bg-white text-slate-700 hover:bg-slate-50"
              }`}
            >
              {a.primary && <ExternalLink className="h-3.5 w-3.5" />}
              {a.label}
            </motion.button>
          ))}
        </motion.div>
      </motion.div>
    </>
  );
}

/* ── Page ───────────────────────────────────────────────────────────────── */
export default function NotificationsPage() {
  const { notifications, unreadCount, markRead, markAllRead } = useNotifications();

  const [activeTab,      setActiveTab]      = useState<Tab>("All");
  const [search,         setSearch]         = useState("");
  const [priorityFilter, setPriorityFilter] = useState("All Priorities");
  const [page,           setPage]           = useState(1);
  const [selected,       setSelected]       = useState<Notification | null>(null);

  /* Open detail and mark read */
  const openDetail = useCallback((n: Notification) => {
    setSelected(n);
    if (n.status === "unread") markRead(n.id);
  }, [markRead]);

  const closeDetail = useCallback(() => setSelected(null), []);

  const readCount = notifications.filter(n => n.status === "read").length;

  function tabMatch(n: Notification): boolean {
    if (activeTab === "All")              return true;
    if (activeTab === "Unread")           return n.status === "unread";
    if (activeTab === "Read")             return n.status === "read";
    if (activeTab === "Order & Delivery") return n.type === "order";
    if (activeTab === "Meal & Menu")      return n.type === "meal";
    if (activeTab === "User & Staff")     return n.type === "user";
    if (activeTab === "Finance")          return n.type === "finance";
    return true;
  }

  const filtered = notifications.filter(n => {
    const matchSearch   = !search || n.title.toLowerCase().includes(search.toLowerCase()) || n.subtitle.toLowerCase().includes(search.toLowerCase());
    const matchPriority = priorityFilter === "All Priorities" || n.priority === priorityFilter.toLowerCase();
    return tabMatch(n) && matchSearch && matchPriority;
  });

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const paged      = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <FadeIn className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-900">Notifications</h1>
          <p className="mt-0.5 text-sm text-slate-500">Manage and monitor all system notifications.</p>
        </div>
        <Button size="sm" icon={Plus}>New Notification</Button>
      </FadeIn>

      {/* Tab bar */}
      <FadeIn className="flex flex-wrap gap-1 overflow-x-auto">
        {TABS.map(tab => (
          <motion.button
            key={tab}
            type="button"
            onClick={() => { setActiveTab(tab); setPage(1); }}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-xs font-semibold transition-colors ${
              activeTab === tab
                ? "bg-indigo-600 text-white shadow-sm"
                : "border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
            }`}
          >
            {tab}
            {tab === "Unread" && unreadCount > 0 && (
              <motion.span
                key={unreadCount}
                initial={{ scale: 0.7 }}
                animate={{ scale: 1 }}
                className="ml-1.5 inline-flex h-4 w-4 items-center justify-center rounded-full bg-rose-500 text-[9px] font-bold text-white"
              >
                {unreadCount}
              </motion.span>
            )}
          </motion.button>
        ))}
      </FadeIn>

      {/* Main content */}
      <div className="grid grid-cols-1 gap-5 lg:grid-cols-4">
        {/* Notifications list — shrinks when detail is open on desktop */}
        <motion.div
          layout
          transition={{ type: "spring", stiffness: 300, damping: 30 }}
          className={`flex flex-col gap-4 ${selected ? "lg:col-span-2" : "lg:col-span-3"}`}
        >
          {/* Search + filter bar */}
          <SlideUp className="flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-sm">
            <div className="relative flex-1 min-w-[160px]">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                value={search}
                onChange={e => { setSearch(e.target.value); setPage(1); }}
                placeholder="Search notifications…"
                className="w-full rounded-lg border border-slate-200 bg-slate-50 py-1.5 pl-9 pr-3 text-sm placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>
            <select
              value={priorityFilter}
              onChange={e => { setPriorityFilter(e.target.value); setPage(1); }}
              className="rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-xs text-slate-600 focus:outline-none"
            >
              {["All Priorities", "High", "Medium", "Low"].map(o => <option key={o}>{o}</option>)}
            </select>
            <button
              type="button"
              className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50 transition-colors"
            >
              <Filter className="h-3.5 w-3.5" />Filters
            </button>
          </SlideUp>

          {/* Rows */}
          <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
            <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3">
              <p className="text-xs font-medium text-slate-500">
                {filtered.length} notification{filtered.length !== 1 ? "s" : ""}
              </p>
              {unreadCount > 0 && (
                <button
                  type="button"
                  onClick={markAllRead}
                  className="text-xs font-medium text-indigo-600 hover:text-indigo-500 transition-colors"
                >
                  Mark all as read
                </button>
              )}
            </div>

            {paged.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-slate-400">
                <Bell className="h-8 w-8 mb-2" />
                <p className="text-sm font-medium">No notifications found</p>
              </div>
            ) : (
              <div className="divide-y divide-slate-50">
                <AnimatePresence initial={false}>
                  {paged.map((n, i) => {
                    const Icon     = TYPE_ICON[n.type];
                    const isUnread = n.status === "unread";
                    const isActive = selected?.id === n.id;
                    return (
                      <motion.div
                        key={n.id}
                        layout
                        initial={{ opacity: 0, y: 6 }}
                        animate={{
                          opacity: 1,
                          y: 0,
                          backgroundColor: isActive
                            ? "rgba(238,242,255,0.8)"
                            : isUnread
                            ? "rgba(238,242,255,0.5)"
                            : "rgba(255,255,255,0)",
                        }}
                        transition={{ delay: i * 0.04, duration: 0.3 }}
                        className={`flex items-start gap-3 px-4 py-3.5 transition-colors cursor-pointer hover:bg-slate-50/60 ${isActive ? "ring-1 ring-inset ring-indigo-200" : ""}`}
                        onClick={() => openDetail(n)}
                      >
                        {/* Icon */}
                        <div className={`relative mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${TYPE_BG[n.type]}`}>
                          <Icon className={`h-4 w-4 ${TYPE_ICON_COLOR[n.type]}`} />
                          <AnimatePresence>
                            {isUnread && (
                              <motion.span
                                key="dot"
                                initial={{ scale: 0 }}
                                animate={{ scale: 1 }}
                                exit={{ scale: 0, opacity: 0 }}
                                transition={{ type: "spring", stiffness: 500, damping: 28 }}
                                className="absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full border-2 border-white bg-rose-500"
                              />
                            )}
                          </AnimatePresence>
                        </div>

                        {/* Text */}
                        <div className="min-w-0 flex-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <motion.p
                              animate={{ fontWeight: isUnread ? 700 : 600, color: isUnread ? "#0f172a" : "#374151" }}
                              transition={{ duration: 0.3 }}
                              className="text-xs"
                            >
                              {n.title}
                            </motion.p>
                            <span className={`inline-flex items-center rounded-full border px-1.5 py-0.5 text-[10px] font-semibold capitalize ${PRIORITY_STYLE[n.priority]}`}>
                              {n.priority}
                            </span>
                            {isUnread && (
                              <motion.span
                                initial={{ opacity: 0, scale: 0.8 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.8 }}
                                className="rounded-full bg-indigo-100 px-1.5 py-0.5 text-[9px] font-bold text-indigo-700"
                              >
                                NEW
                              </motion.span>
                            )}
                          </div>
                          <p className="mt-0.5 text-[11px] text-slate-500 leading-relaxed">{n.subtitle}</p>
                          <div className="mt-1 flex items-center gap-3 text-[10px] text-slate-400">
                            <span>{n.module}</span>
                            <span>·</span>
                            <span>{n.date}</span>
                          </div>
                        </div>

                        {/* Actions */}
                        <div className="flex shrink-0 items-center gap-1">
                          <AnimatePresence>
                            {isUnread && (
                              <motion.button
                                key="mark-read"
                                initial={{ opacity: 0, scale: 0.7 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0, scale: 0.7 }}
                                whileHover={{ scale: 1.1 }}
                                whileTap={{ scale: 0.9 }}
                                type="button"
                                onClick={e => { e.stopPropagation(); markRead(n.id); }}
                                className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-indigo-600 transition-colors"
                                title="Mark as read"
                              >
                                <CheckCircle2 className="h-3.5 w-3.5" />
                              </motion.button>
                            )}
                          </AnimatePresence>
                          <motion.div
                            animate={{ x: isActive ? 2 : 0, color: isActive ? "#6366f1" : "#94a3b8" }}
                            whileHover={{ x: 2 }}
                            className="rounded-lg p-1.5"
                          >
                            <ChevronRight className="h-3.5 w-3.5" />
                          </motion.div>
                        </div>
                      </motion.div>
                    );
                  })}
                </AnimatePresence>
              </div>
            )}

            {/* Pagination */}
            <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-xs text-slate-500">
              <span>Showing {paged.length} of {filtered.length}</span>
              <div className="flex items-center gap-1">
                {Array.from({ length: totalPages }, (_, i) => i + 1).map(p => (
                  <motion.button
                    key={p}
                    whileTap={{ scale: 0.92 }}
                    type="button"
                    onClick={() => setPage(p)}
                    className={`h-6 w-6 rounded text-[11px] font-medium transition-colors ${
                      p === page ? "bg-indigo-600 text-white" : "text-slate-600 hover:bg-slate-100"
                    }`}
                  >
                    {p}
                  </motion.button>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Right column: detail panel (desktop inline) OR sidebar stats */}
        <AnimatePresence mode="wait">
          {selected ? (
            /* Desktop: inline detail panel replacing sidebar */
            <motion.div
              key="detail"
              initial={{ opacity: 0, x: 24 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 24 }}
              transition={{ type: "spring", stiffness: 340, damping: 32 }}
              className="hidden lg:block lg:col-span-2"
            >
              <DetailPanel notification={selected} onClose={closeDetail} />
            </motion.div>
          ) : (
            /* Desktop: normal sidebar */
            <motion.div
              key="sidebar"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="hidden lg:flex lg:col-span-1 lg:flex-col lg:gap-4"
            >
              <SidebarStats
                total={notifications.length}
                unread={unreadCount}
                read={readCount}
                markAllRead={markAllRead}
              />
            </motion.div>
          )}
        </AnimatePresence>

        {/* Mobile: detail panel slides over everything */}
        <AnimatePresence>
          {selected && (
            <DetailPanel key="mobile-detail" notification={selected} onClose={closeDetail} />
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

/* ── Sidebar stats (extracted so it can be swapped out) ─────────────────── */
function SidebarStats({
  total, unread, read, markAllRead,
}: {
  total: number; unread: number; read: number; markAllRead: () => void;
}) {
  return (
    <>
      {/* Summary */}
      <ScaleIn className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <h2 className="mb-3 text-sm font-semibold text-slate-900">Notification Summary</h2>
        <StaggerContainer className="flex flex-col gap-2">
          {[
            { label: "Total",  val: total,  color: "bg-indigo-500" },
            { label: "Unread", val: unread, color: "bg-rose-500"   },
            { label: "Read",   val: read,   color: "bg-emerald-500"},
          ].map(s => (
            <StaggerItem key={s.label}>
              <div className="flex items-center justify-between rounded-lg border border-slate-100 px-3 py-2">
                <div className="flex items-center gap-2">
                  <span className={`h-2 w-2 rounded-full ${s.color}`} />
                  <span className="text-xs font-medium text-slate-600">{s.label}</span>
                </div>
                <motion.span
                  key={s.val}
                  initial={{ opacity: 0, y: -4 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="text-sm font-bold text-slate-900"
                >
                  {s.val}
                </motion.span>
              </div>
            </StaggerItem>
          ))}
        </StaggerContainer>
      </ScaleIn>

      {/* By Channel */}
      <ScaleIn delay={0.04} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <h2 className="mb-2 text-sm font-semibold text-slate-900">By Channel</h2>
        <div className="relative flex items-center justify-center">
          <div className="h-36 w-36">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={CHANNEL_DATA}
                  cx="50%" cy="50%"
                  innerRadius={38} outerRadius={58}
                  dataKey="value"
                  paddingAngle={3}
                >
                  {CHANNEL_DATA.map((d, i) => <Cell key={i} fill={d.color} />)}
                </Pie>
                <Tooltip contentStyle={{ fontSize: 12, borderRadius: 8, border: "1px solid #e2e8f0" }} />
              </PieChart>
            </ResponsiveContainer>
            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
              <p className="text-xl font-bold text-slate-900">{CHANNEL_DATA.reduce((s, d) => s + d.value, 0)}</p>
              <p className="text-[10px] text-slate-400">Total</p>
            </div>
          </div>
        </div>
        <div className="mt-3 flex flex-col gap-1.5">
          {CHANNEL_DATA.map(d => (
            <div key={d.name} className="flex items-center justify-between text-xs">
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 shrink-0 rounded-full" style={{ background: d.color }} />
                <span className="text-slate-600">{d.name}</span>
              </div>
              <span className="font-semibold text-slate-900">{d.value}</span>
            </div>
          ))}
        </div>
      </ScaleIn>

      {/* Quick actions */}
      <SlideUp delay={0.08} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <h2 className="mb-3 text-sm font-semibold text-slate-900">Quick Actions</h2>
        <div className="flex flex-col gap-2">
          {[
            { label: "Mark All as Read",       icon: CheckCircle2, action: markAllRead },
            { label: "Notification Templates", icon: Mail,         action: undefined   },
            { label: "Notification Settings",  icon: Settings,     action: undefined   },
          ].map(a => {
            const Icon = a.icon;
            return (
              <motion.button
                key={a.label}
                whileHover={{ x: 2 }}
                type="button"
                onClick={a.action}
                className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50 transition-colors text-left"
              >
                <Icon className="h-3.5 w-3.5 text-slate-400" />{a.label}
              </motion.button>
            );
          })}
        </div>
      </SlideUp>
    </>
  );
}
